using Api.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Api.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202608120001_SeparateAccountIdentities")]
public sealed class SeparateAccountIdentities : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS products (
                "Id" uuid PRIMARY KEY,
                "Name" varchar(150) NOT NULL,
                "Description" varchar(2000),
                "Price" numeric(10,2) NOT NULL,
                "ImageUrl" text,
                "Category" varchar(80) NOT NULL,
                "StockQuantity" integer NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL
            );
            CREATE INDEX IF NOT EXISTS "IX_products_Category" ON products ("Category");

            CREATE TABLE IF NOT EXISTS orders (
                "Id" uuid PRIMARY KEY,
                "CustomerName" varchar(150) NOT NULL,
                "CustomerEmail" varchar(200) NOT NULL,
                "CustomerCpf" varchar(20),
                "CustomerPhone" varchar(20),
                "CustomerCep" varchar(10),
                "CustomerAddress" varchar(300),
                "PaymentMethod" varchar(30) NOT NULL,
                "Status" varchar(20) NOT NULL,
                "TotalAmount" numeric(10,2) NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "CancelledAt" timestamp with time zone
            );
            CREATE INDEX IF NOT EXISTS "IX_orders_CustomerEmail" ON orders ("CustomerEmail");

            CREATE TABLE IF NOT EXISTS order_items (
                "Id" uuid PRIMARY KEY,
                "OrderId" uuid NOT NULL REFERENCES orders ("Id") ON DELETE CASCADE,
                "ProductId" uuid NOT NULL,
                "ProductName" varchar(150) NOT NULL,
                "UnitPrice" numeric(10,2) NOT NULL,
                "Quantity" integer NOT NULL
            );
            CREATE INDEX IF NOT EXISTS "IX_order_items_OrderId" ON order_items ("OrderId");

            CREATE TABLE IF NOT EXISTS marketplace_accounts (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Email" varchar(200) NOT NULL,
                "PasswordHash" text NOT NULL,
                "FullName" varchar(150) NOT NULL,
                "Cpf" varchar(20),
                "Phone" varchar(20),
                "Cep" varchar(10),
                "Address" varchar(300)
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_marketplace_accounts_Email" ON marketplace_accounts ("Email");

            CREATE TABLE IF NOT EXISTS administrative_accounts (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Email" varchar(200) NOT NULL,
                "PasswordHash" text NOT NULL,
                "FullName" varchar(150) NOT NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_administrative_accounts_Email" ON administrative_accounts ("Email");

            CREATE TABLE IF NOT EXISTS marketplace_refresh_tokens (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "TokenHash" text NOT NULL,
                "MarketplaceAccountId" integer NOT NULL REFERENCES marketplace_accounts ("Id") ON DELETE CASCADE,
                "ExpiresAt" timestamp with time zone NOT NULL,
                "Revoked" boolean NOT NULL DEFAULT false,
                "CreatedAt" timestamp with time zone NOT NULL
            );
            CREATE INDEX IF NOT EXISTS "IX_marketplace_refresh_tokens_MarketplaceAccountId"
                ON marketplace_refresh_tokens ("MarketplaceAccountId");

            CREATE TABLE IF NOT EXISTS administrative_refresh_tokens (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "TokenHash" text NOT NULL,
                "AdministrativeAccountId" integer NOT NULL REFERENCES administrative_accounts ("Id") ON DELETE CASCADE,
                "ExpiresAt" timestamp with time zone NOT NULL,
                "Revoked" boolean NOT NULL DEFAULT false,
                "CreatedAt" timestamp with time zone NOT NULL
            );
            CREATE INDEX IF NOT EXISTS "IX_administrative_refresh_tokens_AdministrativeAccountId"
                ON administrative_refresh_tokens ("AdministrativeAccountId");

            DO $migration$
            BEGIN
                IF to_regclass('public.users') IS NOT NULL THEN
                    ALTER TABLE users ADD COLUMN IF NOT EXISTS user_type varchar(20) NOT NULL DEFAULT 'Client';

                    INSERT INTO marketplace_accounts ("Email", "PasswordHash", "FullName", "Cpf", "Phone", "Cep", "Address")
                    SELECT "Email", "PasswordHash", COALESCE("FullName", "Email"), "Cpf", "Phone", "Cep", "Address"
                    FROM users
                    WHERE COALESCE(user_type, 'Client') <> 'Admin'
                    ON CONFLICT ("Email") DO NOTHING;

                    INSERT INTO administrative_accounts ("Email", "PasswordHash", "FullName")
                    SELECT "Email", "PasswordHash", COALESCE("FullName", "Email")
                    FROM users
                    WHERE user_type = 'Admin'
                    ON CONFLICT ("Email") DO NOTHING;

                    IF to_regclass('public.refresh_tokens') IS NOT NULL THEN
                        INSERT INTO marketplace_refresh_tokens
                            ("TokenHash", "MarketplaceAccountId", "ExpiresAt", "Revoked", "CreatedAt")
                        SELECT token."TokenHash", account."Id", token."ExpiresAt", token."Revoked", token."CreatedAt"
                        FROM refresh_tokens token
                        JOIN users legacy ON legacy."Id" = token."UserId"
                        JOIN marketplace_accounts account ON account."Email" = legacy."Email"
                        WHERE COALESCE(legacy.user_type, 'Client') <> 'Admin';

                        INSERT INTO administrative_refresh_tokens
                            ("TokenHash", "AdministrativeAccountId", "ExpiresAt", "Revoked", "CreatedAt")
                        SELECT token."TokenHash", account."Id", token."ExpiresAt", token."Revoked", token."CreatedAt"
                        FROM refresh_tokens token
                        JOIN users legacy ON legacy."Id" = token."UserId"
                        JOIN administrative_accounts account ON account."Email" = legacy."Email"
                        WHERE legacy.user_type = 'Admin';

                        DROP TABLE refresh_tokens;
                    END IF;

                    DROP TABLE users;
                END IF;
            END $migration$;
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS users (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Email" varchar(200) NOT NULL UNIQUE,
                "PasswordHash" text NOT NULL,
                "FullName" varchar(150) NOT NULL,
                "Cpf" text,
                "Phone" text,
                "Cep" text,
                "Address" text,
                user_type varchar(20) NOT NULL DEFAULT 'Client'
            );

            INSERT INTO users ("Email", "PasswordHash", "FullName", "Cpf", "Phone", "Cep", "Address", user_type)
            SELECT "Email", "PasswordHash", "FullName", "Cpf", "Phone", "Cep", "Address", 'Client'
            FROM marketplace_accounts ON CONFLICT ("Email") DO NOTHING;

            INSERT INTO users ("Email", "PasswordHash", "FullName", user_type)
            SELECT "Email", "PasswordHash", "FullName", 'Admin'
            FROM administrative_accounts ON CONFLICT ("Email") DO NOTHING;

            DROP TABLE IF EXISTS marketplace_refresh_tokens;
            DROP TABLE IF EXISTS administrative_refresh_tokens;
            DROP TABLE IF EXISTS marketplace_accounts;
            DROP TABLE IF EXISTS administrative_accounts;
            """);
    }
}
