server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # 1. Rota principal: Se for a página, tenta achar o arquivo ou joga para o index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. Rota específica para arquivos estáticos (CSS, JS, imagens)
    # Diz explicitamente para o Nginx procurar no disco e dar 404 se não achar,
    # evitando que o Nginx tente mandar isso para o backend.
    location ~* \.(css|js|ico|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot)$ {
        try_files $uri =404;
        expires 1d;
        access_log off;
    }

    # 3. Proxy Reverso APENAS para o Backend
    location /api/ {
        proxy_pass http://backend:8080;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
