services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    environment:
      DB_CONNECTION_STRING: "Host=shopmicro.celueuy02qao.us-east-1.rds.amazonaws.com;Port=5432;Database=shopdb;Username=postgres;Password=postgres;SSL Mode=VerifyFull;Root Certificate=./global-bundle.pem"
      CORS_ALLOWED_ORIGINS: "*"
      ENABLE_SWAGGER: "true"
    # Removido o bloco 'ports' do backend para blindá-lo e torná-lo privado

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80" # Mapeia a porta 80 da sua máquina/ALB para a porta 80 do Nginx no container
    depends_on:
      - backend

